[package]
name = "x-imu3-self-test"
version = "1.2.0"
authors = ["x-io Technologies Limited <info@x-io.co.uk>"]
edition = "2018"

[dependencies]
colour = "2.1.0"
serde_json = "1.0.145"
ximu3 = "1.7.2"
